### ISSUE TITLE
library doesn't compile (Sparkfun ESP32 Thing Plus)

### ISSUE THREAD

**Issue by jefke-glider** [DFRobot/DFRobot_DS323X#1]
following error rises:

home/jpe/Arduino/libraries/DFRobot_DS323X-master/DFRobot_DS323X.cpp:52:51: error: cannot declare member function 'static uint8_t DFRobot_DS323X::bcd2bin(uint8_t)' to have static linkage [-fpermissive]
 static uint8_t DFRobot_DS323X::bcd2bin(uint8_t val)
                                                   ^
/home/jpe/Arduino/libraries/DFRobot_DS323X-master/DFRobot_DS323X.cpp:57:52: error: cannot declare member function 'static uint8_t DFRobot_DS323X::bin2bcd(uint8_t)' to have static linkage [-fpermissive]
 static uint8_t DFRobot_DS323X::bin2bcd (uint8_t val)
                                                    ^

exit status 1

Compilation error: exit status 1

**Comment by davidbroughsmyth** [comment]
Same here. Even tried it with the DFRobot Firebeetle

**Comment by wxzed** [comment]
I apologize for the delayed response. The issue has already been resolved.
